    #klitoris-synonyme
SEARCHTERMS = ['bulboklitoralorgan*',
			'clit',
			'clitor*',
			'kitzel*',
			'kitzler*',
			'klit',
			'klitor*',
			'lustknospe*',
			'lustorgan*',
			'lustperle*',
			'"penis muliebre"',
					
    #vulva-synonyme
			'cunnus',
			'fotze*',
			'foz',
			'fud',
			'fut',
			'intimbereich*',
			'intimgegend*',
			'intimzone*',
			'"miss brown"',
			'möse*',
			'pubes*',
			'"pudendum muliebre"',
			'punzel*',
			'pussi*',
			'pussy*',
			'schamgegend*',
			'scheidenvorhof*',
			'vestibulum',
			'"vorhof d* scheide*"',
			'"vorhof d* vagina*"',
			'votze*',
			'vulv*',
			'"weiblich* scham*"',
			'yoni*',

    #geschlechtsorgan-synonyme
            '*genital*',
			'begattungsorgan*',
			'fortpflanzungsapparat*',
			'fortpflanzungsorgan*',
			'fruchtbarkeitsorgan*',
			'gemächt*',
			'generationsorgan*',
			'geschlechtsapparat*',
			'geschlechtsorgan*',
			'geschlechtsteil*',
			'geschlechtswerkzeug*',
			'intimorgan*',
			'liebesorgan*',
			'"primär* geschlechtsmerkmal*"',
			'pudendum',
			'reproduktionsorgan*',
			'schamteil*',
			'sexualapparat*',
			'sexualorgan*',
			'wollustorgan*',
			'zeugungsorgan*']
                
SEARCHSTRING = ' or '.join([('inh all ' + s) for s in SEARCHTERMS])